name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./go-kubernetes
          file: ./go-kubernetes/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-kubernetes:${{ env.TAG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
